### ISSUE TITLE
베타 2 적용하니 소스보기에서.. description 이 사라집니다.

### ISSUE THREAD

**Issue by wookho** [YJSoft/xe-module-seo#1]
문서영역이 아닌 게시판 혹은 페이지 영역에서 description 이 잘 나왔던 부분이 사라졌습니다.
다국어에 한국어에 넣어도 안나오고 다국어를 사용하지 않아도 항목 자체가 나오지 않네요.

**Comment by YJSoft** [comment]
fixed 7899d6be9bd7977687c4f4a50fb49e9e82b60769
베타3 ( https://github.com/YJSoft/xe-module-seo/releases/tag/v0.3-beta.3 ) 적용해주세요.

**Comment by wookho** [comment]
@YJSoft 감사합니다. 잘 처리 되었네요.
