### ISSUE TITLE
SEO 모듈이 1.8.0 새로 나왔던데요..

### ISSUE THREAD

**Issue by wookho** [YJSoft/xe-module-seo#4]
Meta description 최적화 기능 사용

이 기능이 포함되어서 나왔나요??

혹시 1.8.0 과 합쳐진 버전이 새롭가 나오게 되면 그것을 설치하면 되는건가요?
궁금해서 문의드렸습니다.

**Comment by YJSoft** [comment]
@wookho 아뇨. 없을겁니다.
거의 버려졌다고 생각해서 따로 fork했는데 버전업이 되었으니 조만간 버전업된 것에 맞추어 재작성해서 PR 넣어보겠습니다. 반영이 될지 안될진 모르겠네요.

**Comment by YJSoft** [comment]
@wookho 일단 1.8.0의 변경사항은 이미 `feature/menudesc`에 반영되어 있습니다.
[1.8.0-menudesc](https://github.com/YJSoft/xe-module-seo/releases/tag/1.8.0-menudesc) 버전이 합쳐진 버전입니다.

**Comment by wookho** [comment]
감사합니다. 그럼 위 링크해주신 것으로 설치하면 되는 것이군요. 그것으로 설치하겠습니다.
